### ISSUE TITLE
R package building request

### ISSUE THREAD

**Issue by drizztxx** [UoS-CODeM/GA-Toolbox#1]
Hi,

I used this toolbox to complete my master's graduation design. It's very powerful, while a little inconvenient when used combined with R (the matlabr package and MATLAB are required). So I rewrote and refactored the MATLAB codes into R and integrated them into a [R package](https://github.com/drizztxx/gatbxr).

I want to release this R package to CRAN. Could I get your permission to do this job?

Best regards,
David

**Comment by YimingYAN** [comment]
Hi David, I believe you have already received an email confirmation from our team. So I am now closing this request.
